title: Issue 01
author: Saxlanuit
email: baylie.adams@icloud.com
description: > # this means to ignore newlines until "baseurl:"
 Austin Butler Plays Tenor Sax in a Bathroom Stall

# social links
instagram_username: Saxlanuit
github_username:  Saxlanuit
show_excerpts: true # set to false to remove excerpts on the homepage
